### ISSUE TITLE
Initialize Project

### ISSUE THREAD

**Issue by GlennKintscher** [KatastrophenTeam/BreaktimeSnack#1]
### Background
Before we start coding, we should create the basic Maven project structure and configure automatic builds and tests to ensure high-quality code. 

### Tasks
- [x] Create _README.md_ with project information
- [x] Create _LICENSE.md_ with GNU GPL v3
- [x] Create _.github/AUTHORS.md_ with commiters and contributors
- [x] Create _.github/CHANGELOG.md_ with version history and changes
- [x] Create _.github/CODE_OF_CONDUCT.md_ with rules for contributing
- [x] Create _.github/CONTRIBUTING.md_ with information and guidelines of contributing
- [x] Create _.github/ISSUE_TEMPLATE.md_ with the basic issue layout including checklists
- [x] Create _.github/JAVA_CONVENTIONS.md_ with our code conventions
- [x] Create _.github/PULL_REQUEST_TEMPLATE_ the basic pull request layout including checklists
- [x] Create _.gitignore_ that ignores everything but project files
- [x] Create _pom.xml_ with project information, dependencies and integrations
- [x] Create _.appveyor.yml_ to build and test the software on Windows
- [x] Link project with AppVeyor
- [x] Create _.bettercodehub.yml_ to keep the software maintainable
- [x] Link project with BetterCodeHub
- [x] Create _.travis.yml_ to build and test the software on Linux and ensure code quality with SonarQube
- [x] Link project with SonarQube
- [x] Link project with Travis-CI
- [x] Create _.zappr.yml_ to assure our git conventions
- [x] Link project with Zappr
- [x] Link project with VersionEye
- [x] Link project with Codecov
- [x] Create _codestyle.xml_ to ensure our code conventions via CheckStyle
- [x] Add CheckStyle to Maven configuration
- [x] Add deploy step to Travis-CI configuration to upload file to Github Release
